name: Build and Deploy to Firebase

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.12.1' 

    - name: Install dependencies
      run: npm install
      working-directory: ../../cloudnest

    - name: Build the project
      run: |
        export CI=false
        npm run build
      working-directory: ../../cloudnest



    - name: Deploy to Firebase
      run: firebase deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      working-directory: ../../cloudnest

